# Generated by Django 5.1.7 on 2025-03-30 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solver", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_number", models.IntegerField()),
                ("question_number", models.IntegerField()),
                ("question_text", models.TextField()),
                ("answer_text", models.TextField()),
                (
                    "keywords",
                    models.TextField(blank=True, help_text="Comma-separated keywords"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="solution",
            old_name="content",
            new_name="answer",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="assignment_type",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="file",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="file",
        ),
        migrations.RemoveField(
            model_name="solution",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="solution",
            name="question",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="solution",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solutions",
                to="solver.assignment",
            ),
        ),
    ]
